pipeline {
    agent any

    environment {

        IMAGE_NAME = 'mohamed1782/simplebackendapp:test'
        TAG = "${test}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build the image using the Dockerfile you created
                    sh "docker build -t ${IMAGE_NAME}:${TAG} -t ${IMAGE_NAME}:latest ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    // Optional: Push to Docker Hub
                    // You need to ensure you have docker login configured on the Jenkins agent
                    // sh "docker push ${IMAGE_NAME}:${TAG}"
                    // sh "docker push ${IMAGE_NAME}:latest"
                    echo "Build successful! Docker image created: ${IMAGE_NAME}:${TAG}"
                }
            }
        }
    }

    post {
        always {
            cleanWs() // Clean up the workspace after the job finishes
        }
    }
}s