pipeline {
    agent any

    environment {
        IMAGE_NAME = "mohamed1782/simplebackendapp"
        IMAGE_TAG  = "${BUILD_NUMBER}"   // كل build له tag مختلف، مش latest ثابت
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
             steps {
                 dir('jenkins_first_task/app') {
                     sh 'docker build -t mohamed1782/simplebackendapp:${BUILD_NUMBER} .'
        }
    }
}



        stage('Debug Kube Access') {
           steps {
             sh 'echo $PATH'
             sh 'which kubectl || echo "kubectl NOT FOUND"'
             sh 'which docker || echo "docker NOT FOUND"'
             sh 'kubectl get nodes || echo "KUBECTL FAILED"'
    }
}
        

        stage('Deploy to Minikube') {
            steps {
               dir('jenkins_first_task/k8s'){ sh '''
                    sed -i "s|image:.*|image: $IMAGE_NAME:$IMAGE_TAG|" deployment.yaml
                    kubectl apply -f deployment.yaml
                '''}
            }
        }
    }
}